name: ai_life_admin
description: "Mobile-first MVP for AI Life Admin."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  flutter_local_notifications: ^19.4.0
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0
  shared_preferences: ^2.5.3
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
