import 'models.dart';

const Set<String> kStapleIngredients = <String>{
  'salt',
  'pepper',
  'olive oil',
  'vegetable oil',
  'chili flakes',
  'italian seasoning',
  'cumin',
  'paprika',
  'soy sauce',
};

const List<String> kPantrySuggestions = <String>[
  'chicken',
  'spinach',
  'broccoli',
  'bell pepper',
  'tortillas',
  'rice',
  'black beans',
  'pasta',
  'eggs',
  'cheddar',
  'potatoes',
  'carrots',
  'yogurt',
];

PlannerState seedPlannerState() {
  return const PlannerState(
    preferences: Preferences.seed,
    pantry: <PantryItem>[
      PantryItem(
        id: 'p1',
        name: 'chicken',
        quantityState: QuantityState.some,
        urgency: ItemUrgency.useSoon,
      ),
      PantryItem(
        id: 'p2',
        name: 'spinach',
        quantityState: QuantityState.some,
        urgency: ItemUrgency.useSoon,
      ),
      PantryItem(
        id: 'p3',
        name: 'rice',
        quantityState: QuantityState.full,
        urgency: ItemUrgency.shelfStable,
      ),
      PantryItem(
        id: 'p4',
        name: 'black beans',
        quantityState: QuantityState.some,
        urgency: ItemUrgency.shelfStable,
      ),
      PantryItem(
        id: 'p5',
        name: 'broccoli',
        quantityState: QuantityState.low,
        urgency: ItemUrgency.useSoon,
      ),
      PantryItem(
        id: 'p6',
        name: 'tortillas',
        quantityState: QuantityState.some,
        urgency: ItemUrgency.unknown,
      ),
      PantryItem(
        id: 'p7',
        name: 'cheddar',
        quantityState: QuantityState.low,
        urgency: ItemUrgency.unknown,
      ),
    ],
    plan: <PlannedMeal>[],
    lastPlanSummary: '',
  );
}

List<MealTemplate> buildMealTemplates() {
  return const <MealTemplate>[
    MealTemplate(
      id: 'chicken_stir_fry',
      title: 'Chicken Broccoli Stir-Fry',
      pattern: 'Stir-fry',
      minutes: 25,
      costRank: 2,
      healthRank: 4,
      vegetarian: false,
      tags: <String>['weeknight', 'stir-fry', 'pantry-first'],
      ingredients: <MealIngredient>[
        MealIngredient(name: 'chicken', quantity: '1 lb', aisle: Aisle.protein),
        MealIngredient(
          name: 'broccoli',
          quantity: '2 heads',
          aisle: Aisle.produce,
        ),
        MealIngredient(name: 'rice', quantity: '1 bag', aisle: Aisle.pantry),
        MealIngredient(
          name: 'soy sauce',
          quantity: '1 bottle',
          aisle: Aisle.pantry,
          optionalStaple: true,
        ),
        MealIngredient(
          name: 'garlic',
          quantity: '1 bulb',
          aisle: Aisle.produce,
        ),
      ],
      steps: <String>[
        'Cook the rice first so it is ready when the stir-fry finishes.',
        'Slice the chicken and broccoli into quick-cooking pieces.',
        'Brown the chicken in oil, then add broccoli and garlic.',
        'Stir in soy sauce with a splash of water and cook until glossy.',
        'Serve over rice.',
      ],
    ),
    MealTemplate(
      id: 'black_bean_tacos',
      title: 'Black Bean Veggie Tacos',
      pattern: 'Tacos',
      minutes: 20,
      costRank: 1,
      healthRank: 3,
      vegetarian: true,
      tags: <String>['tacos', 'cheap', 'vegetarian'],
      ingredients: <MealIngredient>[
        MealIngredient(
          name: 'black beans',
          quantity: '2 cans',
          aisle: Aisle.pantry,
        ),
        MealIngredient(
          name: 'tortillas',
          quantity: '1 pack',
          aisle: Aisle.bakery,
        ),
        MealIngredient(
          name: 'bell pepper',
          quantity: '2 peppers',
          aisle: Aisle.produce,
        ),
        MealIngredient(
          name: 'onion',
          quantity: '1 onion',
          aisle: Aisle.produce,
        ),
        MealIngredient(
          name: 'cheddar',
          quantity: '1 bag shredded',
          aisle: Aisle.dairy,
        ),
        MealIngredient(
          name: 'cumin',
          quantity: '1 jar',
          aisle: Aisle.pantry,
          optionalStaple: true,
        ),
      ],
      steps: <String>[
        'Saute sliced onion and bell pepper until tender.',
        'Warm the beans with cumin and a splash of water.',
        'Heat the tortillas in a dry skillet or microwave.',
        'Fill with beans, vegetables, and cheddar.',
      ],
    ),
    MealTemplate(
      id: 'sheet_pan_sausage',
      title: 'Sheet-Pan Sausage and Veg',
      pattern: 'Sheet-pan meal',
      minutes: 30,
      costRank: 2,
      healthRank: 3,
      vegetarian: false,
      tags: <String>['sheet-pan', 'fast cleanup'],
      ingredients: <MealIngredient>[
        MealIngredient(
          name: 'chicken sausage',
          quantity: '1 pack',
          aisle: Aisle.protein,
        ),
        MealIngredient(
          name: 'potatoes',
          quantity: '1 bag',
          aisle: Aisle.produce,
        ),
        MealIngredient(
          name: 'broccoli',
          quantity: '1 head',
          aisle: Aisle.produce,
        ),
        MealIngredient(
          name: 'olive oil',
          quantity: '1 bottle',
          aisle: Aisle.pantry,
          optionalStaple: true,
        ),
        MealIngredient(
          name: 'paprika',
          quantity: '1 jar',
          aisle: Aisle.pantry,
          optionalStaple: true,
        ),
      ],
      steps: <String>[
        'Heat the oven to 425 F.',
        'Toss cut potatoes and broccoli with oil and paprika.',
        'Spread everything on a sheet pan with sliced sausage.',
        'Roast until browned and the potatoes are tender.',
      ],
    ),
    MealTemplate(
      id: 'spinach_frittata',
      title: 'Spinach Cheddar Frittata',
      pattern: 'Egg-based dinner',
      minutes: 22,
      costRank: 1,
      healthRank: 4,
      vegetarian: true,
      tags: <String>['eggs', 'leftovers', 'fast'],
      ingredients: <MealIngredient>[
        MealIngredient(name: 'eggs', quantity: '1 dozen', aisle: Aisle.dairy),
        MealIngredient(
          name: 'spinach',
          quantity: '1 box',
          aisle: Aisle.produce,
        ),
        MealIngredient(
          name: 'cheddar',
          quantity: '1 bag shredded',
          aisle: Aisle.dairy,
        ),
        MealIngredient(
          name: 'onion',
          quantity: '1 onion',
          aisle: Aisle.produce,
        ),
      ],
      steps: <String>[
        'Saute onion and spinach until the spinach wilts.',
        'Whisk eggs with a pinch of salt and fold in cheddar.',
        'Pour into an oven-safe skillet with the vegetables.',
        'Cook briefly on the stove, then finish until just set.',
      ],
    ),
    MealTemplate(
      id: 'chickpea_curry',
      title: 'Chickpea Coconut Curry',
      pattern: 'Curry',
      minutes: 30,
      costRank: 2,
      healthRank: 4,
      vegetarian: true,
      tags: <String>['curry', 'warm', 'vegetarian'],
      ingredients: <MealIngredient>[
        MealIngredient(
          name: 'chickpeas',
          quantity: '2 cans',
          aisle: Aisle.pantry,
        ),
        MealIngredient(
          name: 'coconut milk',
          quantity: '1 can',
          aisle: Aisle.pantry,
        ),
        MealIngredient(
          name: 'spinach',
          quantity: '1 box',
          aisle: Aisle.produce,
        ),
        MealIngredient(name: 'rice', quantity: '1 bag', aisle: Aisle.pantry),
        MealIngredient(
          name: 'curry powder',
          quantity: '1 jar',
          aisle: Aisle.pantry,
          optionalStaple: true,
        ),
      ],
      steps: <String>[
        'Start rice if needed.',
        'Simmer chickpeas with coconut milk and curry powder.',
        'Stir in spinach until wilted.',
        'Serve in bowls over rice.',
      ],
    ),
    MealTemplate(
      id: 'turkey_pasta',
      title: 'Turkey Spinach Pasta',
      pattern: 'Pasta',
      minutes: 28,
      costRank: 2,
      healthRank: 3,
      vegetarian: false,
      tags: <String>['pasta', 'comfort'],
      ingredients: <MealIngredient>[
        MealIngredient(
          name: 'ground turkey',
          quantity: '1 lb',
          aisle: Aisle.protein,
        ),
        MealIngredient(name: 'pasta', quantity: '1 box', aisle: Aisle.pantry),
        MealIngredient(
          name: 'spinach',
          quantity: '1 box',
          aisle: Aisle.produce,
        ),
        MealIngredient(
          name: 'marinara',
          quantity: '1 jar',
          aisle: Aisle.pantry,
        ),
        MealIngredient(name: 'parmesan', quantity: '1 tub', aisle: Aisle.dairy),
      ],
      steps: <String>[
        'Boil pasta until just tender.',
        'Brown turkey in a skillet and season simply.',
        'Add marinara and spinach, then simmer until the spinach wilts.',
        'Toss with pasta and finish with parmesan.',
      ],
    ),
    MealTemplate(
      id: 'salmon_bowls',
      title: 'Salmon Rice Bowls',
      pattern: 'Grain bowl',
      minutes: 30,
      costRank: 3,
      healthRank: 5,
      vegetarian: false,
      tags: <String>['healthy', 'grain bowl'],
      ingredients: <MealIngredient>[
        MealIngredient(name: 'salmon', quantity: '1 lb', aisle: Aisle.protein),
        MealIngredient(name: 'rice', quantity: '1 bag', aisle: Aisle.pantry),
        MealIngredient(
          name: 'cucumber',
          quantity: '1 cucumber',
          aisle: Aisle.produce,
        ),
        MealIngredient(
          name: 'carrots',
          quantity: '1 bag',
          aisle: Aisle.produce,
        ),
        MealIngredient(name: 'yogurt', quantity: '1 tub', aisle: Aisle.dairy),
      ],
      steps: <String>[
        'Cook the rice.',
        'Roast or pan-sear the salmon until flaky.',
        'Prep the cucumber and carrots while the salmon cooks.',
        'Build bowls with rice, salmon, vegetables, and yogurt on top.',
      ],
    ),
    MealTemplate(
      id: 'lentil_soup',
      title: 'Lentil Tomato Soup',
      pattern: 'Soup or stew',
      minutes: 35,
      costRank: 1,
      healthRank: 5,
      vegetarian: true,
      tags: <String>['soup', 'cheap', 'leftovers'],
      ingredients: <MealIngredient>[
        MealIngredient(name: 'lentils', quantity: '1 bag', aisle: Aisle.pantry),
        MealIngredient(
          name: 'carrots',
          quantity: '1 bag',
          aisle: Aisle.produce,
        ),
        MealIngredient(
          name: 'celery',
          quantity: '1 bunch',
          aisle: Aisle.produce,
        ),
        MealIngredient(
          name: 'onion',
          quantity: '1 onion',
          aisle: Aisle.produce,
        ),
        MealIngredient(
          name: 'diced tomatoes',
          quantity: '2 cans',
          aisle: Aisle.pantry,
        ),
      ],
      steps: <String>[
        'Saute onion, carrots, and celery until softened.',
        'Add lentils, tomatoes, and water or broth.',
        'Simmer until the lentils are tender.',
        'Season to taste and serve.',
      ],
    ),
    MealTemplate(
      id: 'chicken_wraps',
      title: 'Chicken Yogurt Wraps',
      pattern: 'Tacos/wraps',
      minutes: 18,
      costRank: 2,
      healthRank: 4,
      vegetarian: false,
      tags: <String>['wraps', 'fast'],
      ingredients: <MealIngredient>[
        MealIngredient(name: 'chicken', quantity: '1 lb', aisle: Aisle.protein),
        MealIngredient(
          name: 'tortillas',
          quantity: '1 pack',
          aisle: Aisle.bakery,
        ),
        MealIngredient(
          name: 'cucumber',
          quantity: '1 cucumber',
          aisle: Aisle.produce,
        ),
        MealIngredient(name: 'yogurt', quantity: '1 tub', aisle: Aisle.dairy),
        MealIngredient(
          name: 'lettuce',
          quantity: '1 head',
          aisle: Aisle.produce,
        ),
      ],
      steps: <String>[
        'Cook the chicken in strips with simple seasoning.',
        'Mix yogurt with a squeeze of lemon if you have one.',
        'Fill tortillas with chicken, cucumber, and lettuce.',
        'Spoon yogurt sauce over the wraps.',
      ],
    ),
    MealTemplate(
      id: 'veggie_fried_rice',
      title: 'Veggie Fried Rice',
      pattern: 'Stir-fry',
      minutes: 20,
      costRank: 1,
      healthRank: 3,
      vegetarian: true,
      tags: <String>['rice', 'fast', 'use odds and ends'],
      ingredients: <MealIngredient>[
        MealIngredient(name: 'rice', quantity: '1 bag', aisle: Aisle.pantry),
        MealIngredient(name: 'eggs', quantity: '1 dozen', aisle: Aisle.dairy),
        MealIngredient(
          name: 'carrots',
          quantity: '1 bag',
          aisle: Aisle.produce,
        ),
        MealIngredient(
          name: 'peas',
          quantity: '1 bag frozen',
          aisle: Aisle.frozen,
        ),
        MealIngredient(
          name: 'soy sauce',
          quantity: '1 bottle',
          aisle: Aisle.pantry,
          optionalStaple: true,
        ),
      ],
      steps: <String>[
        'Use cooked rice if you have it, or cook rice ahead and let it steam dry.',
        'Scramble eggs in a large skillet and set aside.',
        'Cook carrots and peas, then add rice and soy sauce.',
        'Fold the eggs back in and cook until hot.',
      ],
    ),
  ];
}
